language: java
jdk:
- oraclejdk8
deploy:
  provider: releases
  api-key:
    secure: HfkbX2Dih9txDRJv0LlFyTPdhmJQ3Bx7ouK1pW+Pv2y1GS9Xy8wtV8r4YMA0JnUltKR7Y/bFw761knnFLYAgg4AVvKjatNIYNznFfnPvJOR5zUqxb5x1vQlcfBpMTfNnZ75M4EUFKtql6rfLMsa7ZSCh4k67Gn0wkIxSMOmqN1uPw0o4wC6laE/ZhoMTXBmuBi8FJsVHNe4NaBbU27tcPOotPkSXkd6O/XrSpu+JGrrFYYdm9jRqy+r4PH54fiNWiS+5WvgvJlwovYiqizdmYuU8cbl9NDOZDaBtKujZgDaZT9RDIe4UBtDzJhFY4tfdHxJpPFLLXEHXprkJ9M7bJjfNRBHC2VJT2eHTXu9sCP3fNS6r6Hcd8rqwEEeCOxZdlOWGPcYUt9rbukrGamfTyOgLbpYE962pnK7sGG9ktZ0vM1cTs+3pXfn2Is6OwikAnpQFke6CauzU5WYfi1jtYvMTDu3RTTt4if3OdM7TVtUfHPGx6Vn+MfDk6pXFCmJJB1PsTrMz4lEUVt6Zc9Sq5/uOnTB12zBMkO0mTREnzVxNcIrhVc4f2VeGEDlo5n1F6bkaXIlxlRhv7WR+JNyAw7DoZl6gfghBQnn3091XeoUNN9A7Bw7UjSCHnfN+qBDSWfCpF8KxEtQS0mi4DBgAZHLSgDSy5L3H2T78ZYbNmhE=
  file_glob: true
  file: target/MyDog-*.jar
  skip_cleanup: true
  on:
    repo: DoggyCraftDK/MyDog
    tags: true
sudo: false
